name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Generate snake.svg
        run: npx snk svg-only --github-user-name ${{ github.repository_owner }} --output dist/snake.svg

      - name: Configure Git
        run: |
          git config --global user.name Akshitsingh-1
          git config --global user.email akshit.ipod@gmail.com

      - name: Push snake.svg to the output branch
        run: |
          git checkout -b output
          git add dist/snake.svg
          git commit -m "Update snake.svg"
          git push origin output
